//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: package.proto
namespace ProtoTest
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private int _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_login")]
  public partial class Res_login : global::ProtoBuf.IExtensible
  {
    public Res_login() {}
    
    private int _m_nResultID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nResultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nResultID
    {
      get { return _m_nResultID; }
      set { _m_nResultID = value; }
    }
    private int _m_nPlayerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nPlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nPlayerID
    {
      get { return _m_nPlayerID; }
      set { _m_nPlayerID = value; }
    }
    private bool _m_iHaveRole;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iHaveRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_iHaveRole
    {
      get { return _m_iHaveRole; }
      set { _m_iHaveRole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Create_role")]
  public partial class Create_role : global::ProtoBuf.IExtensible
  {
    public Create_role() {}
    
    private int _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private bool _checkName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"checkName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool checkName
    {
      get { return _checkName; }
      set { _checkName = value; }
    }
    private bool _wxLogin;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"wxLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool wxLogin
    {
      get { return _wxLogin; }
      set { _wxLogin = value; }
    }
    private string _wxHead = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"wxHead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wxHead
    {
      get { return _wxHead; }
      set { _wxHead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_roleInfo")]
  public partial class Res_roleInfo : global::ProtoBuf.IExtensible
  {
    public Res_roleInfo() {}
    
    private int _resultID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resultID
    {
      get { return _resultID; }
      set { _resultID = value; }
    }
    private int _uin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"enter")]
  public partial class enter : global::ProtoBuf.IExtensible
  {
    public enter() {}
    
    private int _m_nRoomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nRoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nRoomID
    {
      get { return _m_nRoomID; }
      set { _m_nRoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_enter")]
  public partial class Res_enter : global::ProtoBuf.IExtensible
  {
    public Res_enter() {}
    
    private int _m_nResultID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nResultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nResultID
    {
      get { return _m_nResultID; }
      set { _m_nResultID = value; }
    }
    private int _m_iRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iRoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRoomID
    {
      get { return _m_iRoomID; }
      set { _m_iRoomID = value; }
    }
    private byte[] _m_szReasonMessage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_szReasonMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] m_szReasonMessage
    {
      get { return _m_szReasonMessage; }
      set { _m_szReasonMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVE_over")]
  public partial class PVE_over : global::ProtoBuf.IExtensible
  {
    public PVE_over() {}
    
    private bool _m_iWin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_iWin
    {
      get { return _m_iWin; }
      set { _m_iWin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_PVEover")]
  public partial class Res_PVEover : global::ProtoBuf.IExtensible
  {
    public Res_PVEover() {}
    
    private int _m_iOverStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iOverStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOverStatus
    {
      get { return _m_iOverStatus; }
      set { _m_iOverStatus = value; }
    }
    private int _m_iGetExp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iGetExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iGetExp
    {
      get { return _m_iGetExp; }
      set { _m_iGetExp = value; }
    }
    private int _m_iGetGold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iGetGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iGetGold
    {
      get { return _m_iGetGold; }
      set { _m_iGetGold = value; }
    }
    private int _m_iGetDiamond;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iGetDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iGetDiamond
    {
      get { return _m_iGetDiamond; }
      set { _m_iGetDiamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Merge")]
  public partial class Merge : global::ProtoBuf.IExtensible
  {
    public Merge() {}
    
    private int _m_iModeID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iModeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iModeID
    {
      get { return _m_iModeID; }
      set { _m_iModeID = value; }
    }
    private bool _cancel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cancel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cancel
    {
      get { return _cancel; }
      set { _cancel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_merge")]
  public partial class Res_merge : global::ProtoBuf.IExtensible
  {
    public Res_merge() {}
    
    private int _m_nresultid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nresultid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nresultid
    {
      get { return _m_nresultid; }
      set { _m_nresultid = value; }
    }
    private int _m_mapid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_mapid
    {
      get { return _m_mapid; }
      set { _m_mapid = value; }
    }
    private int _m_TableID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"m_TableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_TableID
    {
      get { return _m_TableID; }
      set { _m_TableID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SitDown")]
  public partial class SitDown : global::ProtoBuf.IExtensible
  {
    public SitDown() {}
    
    private int _m_iRoomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iRoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRoomID
    {
      get { return _m_iRoomID; }
      set { _m_iRoomID = value; }
    }
    private int _m_iTableID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iTableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iTableID
    {
      get { return _m_iTableID; }
      set { _m_iTableID = value; }
    }
    private int _m_cSeatID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_cSeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_cSeatID
    {
      get { return _m_cSeatID; }
      set { _m_cSeatID = value; }
    }
    private int _m_iPlayerCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iPlayerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iPlayerCount
    {
      get { return _m_iPlayerCount; }
      set { _m_iPlayerCount = value; }
    }
    private readonly global::System.Collections.Generic.List<bool> _wxLogin = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(5, Name=@"wxLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> wxLogin
    {
      get { return _wxLogin; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _wxHead = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"wxHead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> wxHead
    {
      get { return _wxHead; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGame")]
  public partial class OnGame : global::ProtoBuf.IExtensible
  {
    public OnGame() {}
    
    private byte[] _gameData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] gameData
    {
      get { return _gameData; }
      set { _gameData = value; }
    }
    private int _m_iRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iRoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRoomID
    {
      get { return _m_iRoomID; }
      set { _m_iRoomID = value; }
    }
    private int _m_iTableID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iTableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iTableID
    {
      get { return _m_iTableID; }
      set { _m_iTableID = value; }
    }
    private int _m_icmd;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_icmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_icmd
    {
      get { return _m_icmd; }
      set { _m_icmd = value; }
    }
    private int _gameDataLength;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gameDataLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameDataLength
    {
      get { return _gameDataLength; }
      set { _gameDataLength = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_game")]
  public partial class Res_game : global::ProtoBuf.IExtensible
  {
    public Res_game() {}
    
    private byte[] _gameData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] gameData
    {
      get { return _gameData; }
      set { _gameData = value; }
    }
    private int _m_iRoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iRoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRoomID
    {
      get { return _m_iRoomID; }
      set { _m_iRoomID = value; }
    }
    private int _m_iTableID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iTableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iTableID
    {
      get { return _m_iTableID; }
      set { _m_iTableID = value; }
    }
    private int _m_icmd;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_icmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_icmd
    {
      get { return _m_icmd; }
      set { _m_icmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGameReady")]
  public partial class OnGameReady : global::ProtoBuf.IExtensible
  {
    public OnGameReady() {}
    
    private string _m_strName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strName
    {
      get { return _m_strName; }
      set { _m_strName = value; }
    }
    private int _m_iPic;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iPic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iPic
    {
      get { return _m_iPic; }
      set { _m_iPic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Notify_ready")]
  public partial class Notify_ready : global::ProtoBuf.IExtensible
  {
    public Notify_ready() {}
    
    private int _m_iSeat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iSeat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSeat
    {
      get { return _m_iSeat; }
      set { _m_iSeat = value; }
    }
    private int _m_iPic;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iPic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iPic
    {
      get { return _m_iPic; }
      set { _m_iPic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_ready")]
  public partial class Res_ready : global::ProtoBuf.IExtensible
  {
    public Res_ready() {}
    
    private int _m_iSeatSum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iSeatSum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSeatSum
    {
      get { return _m_iSeatSum; }
      set { _m_iSeatSum = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _m_strName = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"m_strName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> m_strName
    {
      get { return _m_strName; }
    }
  
    private int _m_iMapID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iMapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iMapID
    {
      get { return _m_iMapID; }
      set { _m_iMapID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _m_iTeamID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"m_iTeamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> m_iTeamID
    {
      get { return _m_iTeamID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _m_aiSeatPlayer = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"m_aiSeatPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> m_aiSeatPlayer
    {
      get { return _m_aiSeatPlayer; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGameChoose")]
  public partial class OnGameChoose : global::ProtoBuf.IExtensible
  {
    public OnGameChoose() {}
    
    private int _m_iTankID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iTankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iTankID
    {
      get { return _m_iTankID; }
      set { _m_iTankID = value; }
    }
    private int _m_iSkill1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iSkill1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSkill1
    {
      get { return _m_iSkill1; }
      set { _m_iSkill1 = value; }
    }
    private int _m_iSkill2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iSkill2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSkill2
    {
      get { return _m_iSkill2; }
      set { _m_iSkill2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Notify_choose")]
  public partial class Notify_choose : global::ProtoBuf.IExtensible
  {
    public Notify_choose() {}
    
    private int _m_iTankID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iTankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iTankID
    {
      get { return _m_iTankID; }
      set { _m_iTankID = value; }
    }
    private int _m_iSeat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iSeat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSeat
    {
      get { return _m_iSeat; }
      set { _m_iSeat = value; }
    }
    private int _m_iSkill1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iSkill1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSkill1
    {
      get { return _m_iSkill1; }
      set { _m_iSkill1 = value; }
    }
    private int _m_iSkill2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iSkill2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSkill2
    {
      get { return _m_iSkill2; }
      set { _m_iSkill2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_choose")]
  public partial class Res_choose : global::ProtoBuf.IExtensible
  {
    public Res_choose() {}
    
    private int _m_iRound;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iRound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRound
    {
      get { return _m_iRound; }
      set { _m_iRound = value; }
    }
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _m_iTankID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"m_iTankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> m_iTankID
    {
      get { return _m_iTankID; }
    }
  
    private int _m_iRoundTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iRoundTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRoundTime
    {
      get { return _m_iRoundTime; }
      set { _m_iRoundTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGameLoading")]
  public partial class OnGameLoading : global::ProtoBuf.IExtensible
  {
    public OnGameLoading() {}
    
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private int _m_ilen;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_ilen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ilen
    {
      get { return _m_ilen; }
      set { _m_ilen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_loading")]
  public partial class Res_loading : global::ProtoBuf.IExtensible
  {
    public Res_loading() {}
    
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private int _m_ilen;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_ilen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ilen
    {
      get { return _m_ilen; }
      set { _m_ilen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGameMove")]
  public partial class OnGameMove : global::ProtoBuf.IExtensible
  {
    public OnGameMove() {}
    
    private bool _m_iKeyDown;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iKeyDown", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_iKeyDown
    {
      get { return _m_iKeyDown; }
      set { _m_iKeyDown = value; }
    }
    private int _m_iDirection;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iDirection", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iDirection
    {
      get { return _m_iDirection; }
      set { _m_iDirection = value; }
    }
    private float _m_iIntervalTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iIntervalTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iIntervalTime
    {
      get { return _m_iIntervalTime; }
      set { _m_iIntervalTime = value; }
    }
    private float _m_iPosX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iPosX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iPosX
    {
      get { return _m_iPosX; }
      set { _m_iPosX = value; }
    }
    private float _m_iPosY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"m_iPosY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iPosY
    {
      get { return _m_iPosY; }
      set { _m_iPosY = value; }
    }
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_move")]
  public partial class Res_move : global::ProtoBuf.IExtensible
  {
    public Res_move() {}
    
    private int _m_iRound;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iRound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRound
    {
      get { return _m_iRound; }
      set { _m_iRound = value; }
    }
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private bool _m_iKeyDown;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iKeyDown", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_iKeyDown
    {
      get { return _m_iKeyDown; }
      set { _m_iKeyDown = value; }
    }
    private int _m_iDirection;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iDirection", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iDirection
    {
      get { return _m_iDirection; }
      set { _m_iDirection = value; }
    }
    private float _m_iIntervalTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"m_iIntervalTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iIntervalTime
    {
      get { return _m_iIntervalTime; }
      set { _m_iIntervalTime = value; }
    }
    private float _m_iPosX = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"m_iPosX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float m_iPosX
    {
      get { return _m_iPosX; }
      set { _m_iPosX = value; }
    }
    private float _m_iPosY = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"m_iPosY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float m_iPosY
    {
      get { return _m_iPosY; }
      set { _m_iPosY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_round")]
  public partial class Res_round : global::ProtoBuf.IExtensible
  {
    public Res_round() {}
    
    private int _m_iRound;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iRound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRound
    {
      get { return _m_iRound; }
      set { _m_iRound = value; }
    }
    private int _m_iWind;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iWind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iWind
    {
      get { return _m_iWind; }
      set { _m_iWind = value; }
    }
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGameAttack")]
  public partial class OnGameAttack : global::ProtoBuf.IExtensible
  {
    public OnGameAttack() {}
    
    private int _m_iPower;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iPower
    {
      get { return _m_iPower; }
      set { _m_iPower = value; }
    }
    private float _m_iAngle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iAngle
    {
      get { return _m_iAngle; }
      set { _m_iAngle = value; }
    }
    private bool _m_iHasBlast;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iHasBlast", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_iHasBlast
    {
      get { return _m_iHasBlast; }
      set { _m_iHasBlast = value; }
    }
    private int _m_iBombType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iBombType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iBombType
    {
      get { return _m_iBombType; }
      set { _m_iBombType = value; }
    }
    private int _m_iBombCnt = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"m_iBombCnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_iBombCnt
    {
      get { return _m_iBombCnt; }
      set { _m_iBombCnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_attack")]
  public partial class Res_attack : global::ProtoBuf.IExtensible
  {
    public Res_attack() {}
    
    private int _m_iRound;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iRound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRound
    {
      get { return _m_iRound; }
      set { _m_iRound = value; }
    }
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private int _m_iPower;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iPower
    {
      get { return _m_iPower; }
      set { _m_iPower = value; }
    }
    private float _m_iAngle;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iAngle
    {
      get { return _m_iAngle; }
      set { _m_iAngle = value; }
    }
    private int _m_iBombType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"m_iBombType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iBombType
    {
      get { return _m_iBombType; }
      set { _m_iBombType = value; }
    }
    private int _m_iBombCnt = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"m_iBombCnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_iBombCnt
    {
      get { return _m_iBombCnt; }
      set { _m_iBombCnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGameBoom")]
  public partial class OnGameBoom : global::ProtoBuf.IExtensible
  {
    public OnGameBoom() {}
    
    private float _m_ix;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_ix", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_ix
    {
      get { return _m_ix; }
      set { _m_ix = value; }
    }
    private float _m_iy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iy
    {
      get { return _m_iy; }
      set { _m_iy = value; }
    }
    private bool _Kind;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Kind", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Kind
    {
      get { return _Kind; }
      set { _Kind = value; }
    }
    private int _BombID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"BombID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BombID
    {
      get { return _BombID; }
      set { _BombID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_Boom")]
  public partial class Res_Boom : global::ProtoBuf.IExtensible
  {
    public Res_Boom() {}
    
    private int _m_iRound;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iRound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iRound
    {
      get { return _m_iRound; }
      set { _m_iRound = value; }
    }
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private float _m_ix;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_ix", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_ix
    {
      get { return _m_ix; }
      set { _m_ix = value; }
    }
    private float _m_iy;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_iy
    {
      get { return _m_iy; }
      set { _m_iy = value; }
    }
    private bool _Kind;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Kind", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Kind
    {
      get { return _Kind; }
      set { _Kind = value; }
    }
    private int _BombID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"BombID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BombID
    {
      get { return _BombID; }
      set { _BombID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGame_HP")]
  public partial class OnGame_HP : global::ProtoBuf.IExtensible
  {
    public OnGame_HP() {}
    
    private int _m_iPlayerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iPlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iPlayerID
    {
      get { return _m_iPlayerID; }
      set { _m_iPlayerID = value; }
    }
    private int _hpValues;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hpValues", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpValues
    {
      get { return _hpValues; }
      set { _hpValues = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGameOver")]
  public partial class OnGameOver : global::ProtoBuf.IExtensible
  {
    public OnGameOver() {}
    
    private int _m_iTeamID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iTeamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iTeamID
    {
      get { return _m_iTeamID; }
      set { _m_iTeamID = value; }
    }
    private bool _m_iWin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_iWin
    {
      get { return _m_iWin; }
      set { _m_iWin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_over")]
  public partial class Res_over : global::ProtoBuf.IExtensible
  {
    public Res_over() {}
    
    private int _m_iWinTeamID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iWinTeamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iWinTeamID
    {
      get { return _m_iWinTeamID; }
      set { _m_iWinTeamID = value; }
    }
    private int _m_iOverStatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOverStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOverStatus
    {
      get { return _m_iOverStatus; }
      set { _m_iOverStatus = value; }
    }
    private int _m_iGetExp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_iGetExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iGetExp
    {
      get { return _m_iGetExp; }
      set { _m_iGetExp = value; }
    }
    private int _m_iGetGold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_iGetGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iGetGold
    {
      get { return _m_iGetGold; }
      set { _m_iGetGold = value; }
    }
    private int _m_iGetDiamond;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"m_iGetDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iGetDiamond
    {
      get { return _m_iGetDiamond; }
      set { _m_iGetDiamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Res_quit")]
  public partial class Res_quit : global::ProtoBuf.IExtensible
  {
    public Res_quit() {}
    
    private bool _m_iQuitOk;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iQuitOk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_iQuitOk
    {
      get { return _m_iQuitOk; }
      set { _m_iQuitOk = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Notify_disconnect")]
  public partial class Notify_disconnect : global::ProtoBuf.IExtensible
  {
    public Notify_disconnect() {}
    
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnGame_chat")]
  public partial class OnGame_chat : global::ProtoBuf.IExtensible
  {
    public OnGame_chat() {}
    
    private int _m_iChatID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iChatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iChatID
    {
      get { return _m_iChatID; }
      set { _m_iChatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Notify_chat")]
  public partial class Notify_chat : global::ProtoBuf.IExtensible
  {
    public Notify_chat() {}
    
    private int _m_iChatID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iChatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iChatID
    {
      get { return _m_iChatID; }
      set { _m_iChatID = value; }
    }
    private int _m_iOptID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID
    {
      get { return _m_iOptID; }
      set { _m_iOptID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_add_del")]
  public partial class Friend_add_del : global::ProtoBuf.IExtensible
  {
    public Friend_add_del() {}
    
    private string _m_NameOther;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_NameOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_NameOther
    {
      get { return _m_NameOther; }
      set { _m_NameOther = value; }
    }
    private int _ResultID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ResultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ResultID
    {
      get { return _ResultID; }
      set { _ResultID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_array")]
  public partial class Friend_array : global::ProtoBuf.IExtensible
  {
    public Friend_array() {}
    
    private int _friendCnt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friendCnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friendCnt
    {
      get { return _friendCnt; }
      set { _friendCnt = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _sex = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> sex
    {
      get { return _sex; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _exp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> exp
    {
      get { return _exp; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _online = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(5, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> online
    {
      get { return _online; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _wxLogin = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(6, Name=@"wxLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> wxLogin
    {
      get { return _wxLogin; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _wxHead = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"wxHead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> wxHead
    {
      get { return _wxHead; }
    }
  
    private int _v = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"v", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int v
    {
      get { return _v; }
      set { _v = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_addNotify")]
  public partial class Friend_addNotify : global::ProtoBuf.IExtensible
  {
    public Friend_addNotify() {}
    
    private string _m_NameOther;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_NameOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_NameOther
    {
      get { return _m_NameOther; }
      set { _m_NameOther = value; }
    }
    private int _m_iSex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iSex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iSex
    {
      get { return _m_iSex; }
      set { _m_iSex = value; }
    }
    private bool _online;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool online
    {
      get { return _online; }
      set { _online = value; }
    }
    private bool _wxLogin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"wxLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool wxLogin
    {
      get { return _wxLogin; }
      set { _wxLogin = value; }
    }
    private string _wxHead = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wxHead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wxHead
    {
      get { return _wxHead; }
      set { _wxHead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_delNotify")]
  public partial class Friend_delNotify : global::ProtoBuf.IExtensible
  {
    public Friend_delNotify() {}
    
    private string _m_NameOther;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_NameOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_NameOther
    {
      get { return _m_NameOther; }
      set { _m_NameOther = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_resAddNotify")]
  public partial class Friend_resAddNotify : global::ProtoBuf.IExtensible
  {
    public Friend_resAddNotify() {}
    
    private string _Name1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name1
    {
      get { return _Name1; }
      set { _Name1 = value; }
    }
    private string _Name2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name2
    {
      get { return _Name2; }
      set { _Name2 = value; }
    }
    private bool _accept;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accept", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool accept
    {
      get { return _accept; }
      set { _accept = value; }
    }
    private int _resultID = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resultID
    {
      get { return _resultID; }
      set { _resultID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_getInfo")]
  public partial class Friend_getInfo : global::ProtoBuf.IExtensible
  {
    public Friend_getInfo() {}
    
    private string _m_NameOther;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_NameOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_NameOther
    {
      get { return _m_NameOther; }
      set { _m_NameOther = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_resGetInfo")]
  public partial class Friend_resGetInfo : global::ProtoBuf.IExtensible
  {
    public Friend_resGetInfo() {}
    
    private int _resultID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resultID
    {
      get { return _resultID; }
      set { _resultID = value; }
    }
    private string _m_NameOther = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_NameOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_NameOther
    {
      get { return _m_NameOther; }
      set { _m_NameOther = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _battleCnt = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battleCnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battleCnt
    {
      get { return _battleCnt; }
      set { _battleCnt = value; }
    }
    private int _winCnt = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"winCnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCnt
    {
      get { return _winCnt; }
      set { _winCnt = value; }
    }
    private bool _isOnline = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private bool _wxLogin = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"wxLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool wxLogin
    {
      get { return _wxLogin; }
      set { _wxLogin = value; }
    }
    private string _wxHead = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"wxHead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wxHead
    {
      get { return _wxHead; }
      set { _wxHead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_notifyStatus")]
  public partial class Friend_notifyStatus : global::ProtoBuf.IExtensible
  {
    public Friend_notifyStatus() {}
    
    private string _m_Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Name
    {
      get { return _m_Name; }
      set { _m_Name = value; }
    }
    private bool _online;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool online
    {
      get { return _online; }
      set { _online = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_invitation")]
  public partial class Friend_invitation : global::ProtoBuf.IExtensible
  {
    public Friend_invitation() {}
    
    private string _m_NameOther;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_NameOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_NameOther
    {
      get { return _m_NameOther; }
      set { _m_NameOther = value; }
    }
    private int _m_iOptIDself;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptIDself", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptIDself
    {
      get { return _m_iOptIDself; }
      set { _m_iOptIDself = value; }
    }
    private int _ResultID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ResultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ResultID
    {
      get { return _ResultID; }
      set { _ResultID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_invNotify")]
  public partial class Friend_invNotify : global::ProtoBuf.IExtensible
  {
    public Friend_invNotify() {}
    
    private string _m_NameOther;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_NameOther", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_NameOther
    {
      get { return _m_NameOther; }
      set { _m_NameOther = value; }
    }
    private int _m_iOptIDother;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptIDother", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptIDother
    {
      get { return _m_iOptIDother; }
      set { _m_iOptIDother = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend_resInvNotify")]
  public partial class Friend_resInvNotify : global::ProtoBuf.IExtensible
  {
    public Friend_resInvNotify() {}
    
    private int _m_iOptID1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_iOptID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID1
    {
      get { return _m_iOptID1; }
      set { _m_iOptID1 = value; }
    }
    private int _m_iOptID2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_iOptID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_iOptID2
    {
      get { return _m_iOptID2; }
      set { _m_iOptID2 = value; }
    }
    private bool _accept;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accept", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool accept
    {
      get { return _accept; }
      set { _accept = value; }
    }
    private int _resultID = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resultID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resultID
    {
      get { return _resultID; }
      set { _resultID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}